# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod download
builds:
  - id: "kubectl-profefe"
    main: ./cmd/kubectl-profefe
    binary: kubectl-profefe
    env:
      - CGO_ENABLED=0
  - id: "kprofefe"
    main: ./cmd/kprofefe
    binary: kprofefe
    env:
      - CGO_ENABLED=0
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
dockers:
  - binaries:
      - kprofefe
    goos: linux
    goarch: amd64
    image_templates:
      - "profefe/kprofefe:latest"
      - "profefe/kprofefe:{{ .Tag }}"
    dockerfile: Dockerfile.gorelease
